name: turning_point
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter 
  
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dotted_line: ^3.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  mobile_scanner: ^3.5.5
  page_transition: ^2.1.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  stacked_card_carousel: ^0.0.4
  video_player: ^2.8.1
  google_sign_in: ^6.2.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter 
  
  
  flutter_lints: ^3.0.1


flutter: 
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
