name: turning_point
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter 
  
  animations: ^2.0.11
  animated_splash_screen: ^1.3.0
  audioplayers: ^5.2.1
  awesome_notifications: ^0.9.2
  awesome_notifications_core: ^0.9.1
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^3.0.0
  dio: ^5.4.1
  dropdown_button2: ^2.3.9

#==========Firebase==========#
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.17
  
  flutter_animate: ^4.5.0
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_spinkit: ^5.2.0
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  http: ^1.1.2
  image_picker: ^1.0.7
  jwt_decoder: ^2.0.1
  local_auth: ^2.2.0
  lottie: ^3.1.0
  mobile_scanner: ^4.0.0
  otp_text_field: ^1.1.3
  page_transition: ^2.1.0
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  pinput: ^4.0.0
  scratcher: ^2.5.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  stacked_card_carousel: ^0.0.4
  vibration: ^1.8.4
  video_player: ^2.8.3
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/turning_point_circle_logo.png"
  background_color: "#000000"
  theme_color: "#000000"
  # adaptive_icon_background: "#000000"
  # adaptive_icon_foreground: "assets/images/turning_point_logo.png"



flutter:  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/sounds/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
