name: turning_point
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter 
  
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  page_transition: ^2.1.0
  percent_indicator: ^4.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.0
  video_player: ^2.8.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter 
  
  
  flutter_lints: ^3.0.1


flutter: 
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
