name: turning_point
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter 
  
  animations: ^2.0.11
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9

#==========Firebase==========#
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  http: ^1.1.2
  image_picker: ^1.0.7
  jwt_decoder: ^2.0.1
  mobile_scanner: ^4.0.0
  otp_text_field: ^1.1.3
  page_transition: ^2.1.0
  permission_handler: ^11.2.0
  percent_indicator: ^4.2.3
  photo_view: ^0.14.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.0
  stacked_card_carousel: ^0.0.4
  video_player: ^2.8.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.1


flutter:  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
